name:
channels:
- conda-forge
- defaults
dependencies:
- ca-certificates
- certifi=2017.11.5=py36hf29ccca_0
- decorator=4.1.2=py36hd076ac8_0
- entrypoints=0.2.3=py36h1aec115_2
- html5lib=1.0.1=py36h2f9c1c0_0
- ipykernel=4.7.0=py36h2f9c1c0_0
- ipython=6.2.1=py36h88c514a_1
- ipython_genutils=0.2.0=py36hb52b0d5_0
- jedi=0.11.0=py36_2
- jinja2=2.10=py36ha16c418_0
- jsonschema=2.6.0=py36h006f8b5_0
- jupyter_client=5.1.0=py36h614e9ea_0
- jupyter_core=4.4.0=py36h7c827e3_0
- libedit=3.1=heed3624_0
- libffi=3.2.1=hd88cf55_4
- libsodium=1.0.15=hf101ebd_0
- markupsafe=1.0=py36hd9260cd_1
- mistune=0.8.1=py36h3d5977c_0
- nbconvert=5.3.1=py36hb41ffb7_0
- nbformat=4.4.0=py36h31c9010_0
- notebook=5.0.0=py36_0
- openssl=1.0.2l=0
- pandoc=1.15.0.6=0
- pandocfilters=1.4.2
- parso=0.1.1=py_0
- pexpect=4.2.1=py36_0
- pickleshare=0.7.4=py36_0
- pip=9.0.1=py36_1
- prompt_toolkit=1.0.15=py36_0
- ptyprocess=0.5.2=py36_0
- pygments=2.2.0=py36_0
- python=3.6.2=0
- python-dateutil=2.6.1=py36_0
- pyzmq=16.0.2=py36_0
- readline=6.2=2
- setuptools=36.4.0=py36_1
- simplegeneric=0.8.1=py36_1
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- terminado=0.6=py36_0
- testpath=0.3.1=py36_0
- tk=8.5.18=0
- tornado=4.5.2=py36_0
- traitlets=4.3.2=py36_0
- wcwidth=0.1.7=py36_0
- webencodings=0.5=py36_0
- wheel=0.29.0=py36_0
- xz=5.2.3=0
- zeromq=4.1.5=0
- zlib=1.2.11=0
- pip:
  - bash-kernel==0.7.1
  - ipython-genutils==0.2.0
  - jupyter-client==5.1.0
  - jupyter-core==4.4.0
  - prompt-toolkit==1.0.15

